[mypy]
python_version = 3.12
files = py/src
ignore_missing_imports = True
check_untyped_defs = True
disallow_untyped_defs = True
no_implicit_optional = True
warn_unused_ignores = True
disable_error_code = import-untyped

[mypy-mediafile]
ignore_missing_imports = True

[mypy-mediafile.*]
ignore_missing_imports = True

[mypy-yt_dlp]
ignore_missing_imports = True

[mypy-yt_dlp.*]
ignore_missing_imports = True
